services:
  auth:
    restart: always
    build: ./auth
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=auth_db
      - DB_USER=auth_user
      - DB_PASSWORD=my-sec-pass
    networks:
      - app_net
  ui:
    restart: always
    build: ./UI
    depends_on:
        - auth
        - weather
    environment:
        - Auth_HOST=auth
        - Auth_PORT=8080
        - Weather_HOST=weather
        - Weather_PORT=5000
    ports:
      - "3000:3000"
    networks:
        - app_net

  weather:
    restart: always
    build: ./weather
    environment:
      - API_KEY= 6d92c50bdamsh81137f3b87ace1fp1d53eejsnfe818b9dbc83
    networks:
      - app_net

  db:
    image: mysql:8.0.25
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=my-sec-pass
      - MYSQL_DATABASE=auth_db
    networks:
      - app_net
    volumes:
      - ./db-data:/var/lib/mysql

networks:
  app_net:
    driver: bridge
   
volumes:
  db-data: